### ISSUE TITLE
Não consegui puxar os dados

### ISSUE THREAD

**Issue by rraulison** [thomas-yasuoka/comdinheiro#1]
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~\anaconda3\lib\site-packages\requests\models.py:910, in Response.json(self, **kwargs)
    909 try:
--> 910     return complexjson.loads(self.text, **kwargs)
    911 except JSONDecodeError as e:
    912     # Catch JSON-related errors and raise as requests.JSONDecodeError
    913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~\anaconda3\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File ~\anaconda3\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File ~\anaconda3\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Input In [8], in <cell line: 4>()
      2 url = "https://www.comdinheiro.com.br/HistoricoIndicadoresFundos001.php?&cnpjs=29726133000121+28581166000168&data_ini=16112021&data_fim=07032022&indicadores=patrimonio~cotistas+beta_48m+valor_total+captacao+resgate+valor_cota&op01=tabela_h&num_casas=2&enviar_email=0&periodicidade=diaria&cabecalho_excel=modo2&transpor=0&asc_desc=desc&tipo_grafico=linha&relat_alias_automatico=cmd_alias_01"
      3 ins = make_instrument(usuario, senha, url)
----> 4 ins.get_data()
      5 print(ins.df.head())

File ~\anaconda3\lib\site-packages\comdinheiro\instruments.py:56, in instrument.get_data(self, json_format, tab, debug)
     53     print("data got got")
     54     print(response)
---> 56 self.jsn = response.json()
     57 self.make_df(json_format, tab)

File ~\anaconda3\lib\site-packages\requests\models.py:917, in Response.json(self, **kwargs)
    915     raise RequestsJSONDecodeError(e.message)
    916 else:
--> 917     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: [Errno Expecting value]  Numero maximo de acessos simultaneos atingidos.: 1

**Comment by tyasuok** [comment]
Opa, acredito que, conforma indica a última linha do seu erro, você não conseguiu realizar a request por ter atingido o número máximo de acessos simultâneos do Comdinheiro, lembrando que a API também conta para aquele limite de "cliques" definido.

Tente deslogar de sua conta no navegador antes de realizar a consulta.

Caso o erro persista por favor informe a versão do python e da biblioteca que está usando.

**Comment by rraulison** [comment]
Deu certo! Muito obrigado

A quarta, 29/06/2022, 22:05, thomas-yasuoka ***@***.***>
escreveu:
